version: 2
jobs:
  build-and-test:
    docker:
    - image: cimg/node:18.20.2
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Installer les dépendances
        command: npm ci
    - run:
        name: Build Angular App
        command: npm run build
    - run:
        name: Skipping tests (pas encore en place)
        command: echo "Tests non configurés pour le moment"
workflows:
  version: 2
  default:
    jobs:
    - build-and-test
